export { default as Startup } from './Startup/Startup';
export { default as Example } from './Example/Example';
export { default as Home } from './Home/Home';
export { default as Login } from "./Login/Login";
export { default as Signup } from "./Signup/Signup"
export { default as Interests } from "./Ineterests/Interests";
export { default as Explore } from "./Explore/Explore";
export { default as Chat } from "./Chat/Chat";
export { default as Post } from "./Post/Post";
export { default as Notifications } from "./Notification/Notification";
export { default as Profile } from "./Profile/Profile";
