export { default as Eye } from "@/assets/icons/Eye.svg";
export { default as EyeSlash } from "@/assets/icons/Eye_cut.svg";
export { default as GoogleLogo } from "@/assets/icons/google.svg";
export { default as AppleLogo } from "@/assets/icons/apple.svg";
export { default as ChevronLeft } from "@/assets/icons/chevron_left.svg";
export { default as Cat_Charity } from "@/assets/icons/cat_charity.svg";
export { default as Cat_Cooking } from "@/assets/icons/cat_cooking.svg";
export { default as Cat_Fashioon } from "@/assets/icons/cat_fashion.svg";
export { default as Cat_Gaming } from "@/assets/icons/cat_gaming.svg";
export { default as Cat_Music } from "@/assets/icons/cat_music.svg";
export { default as Cat_Painting } from "@/assets/icons/cat_painting.svg";
export { default as Cat_Photography } from "@/assets/icons/cat_photography.svg";
export { default as Cat_Travel } from "@/assets/icons/cat_travel.svg";
export { default as Cat_Reading } from "@/assets/icons/cat_reading.svg";
export { default as Cat_Speech } from "@/assets/icons/cat_speech.svg";
export { default as Cat_PawPrint } from "@/assets/icons/cat_pawprint.svg";
export { default as Tab_Explore_Default } from "@/assets/icons/tab_explore_default.svg"
export { default as Tab_Explore_Selected } from "@/assets/icons/tab_explore_selected.svg"
export { default as Tab_Chat_Default } from "@/assets/icons/tab_chat_default.svg"
export { default as Tab_Chat_Selected } from "@/assets/icons/tab_chat_selected.svg"
export { default as Tab_Post_Default } from "@/assets/icons/tab_post_default.svg"
export { default as Tab_Notifications_Default } from "@/assets/icons/ta_notifications_default.svg"
export { default as Tab_Notifications_Selected } from "@/assets/icons/tab_notifications_selected.svg"
export { default as Tab_Profile_Default } from "@/assets/icons/tab_profile_default.svg"
export { default as Tab_Profile_Selected } from "@/assets/icons/tabb_profile_selected.svg";
export { default as GridView } from "@/assets/icons/grid_view.svg";
export { default as MapView } from "@/assets/icons/map_view.svg";
export { default as Tick } from "@/assets/icons/tick.svg";
export { default as MenuHr } from "@/assets/icons/menu_icon_hr.svg";
export { default as Cat_Running } from "@/assets/icons/cat_running.svg";
export { default as Heart } from "@/assets/icons/heart.svg";
export { default as Share } from "@/assets/icons/share.svg";
export { default as Cat_Swimming } from "@/assets/icons/cat_swimming.svg";
export { default as Trash } from "@/assets/icons/trash.svg";
export { default as Edit } from "@/assets/icons/edit.svg";
export { default as Search } from "@/assets/icons/search.svg";
export { default as Cat_Running_Left } from "@/assets/icons/cat_running_left.svg";
export { default as Cat_Shopping } from "@/assets/icons/Cat_Shopping.svg";
export { default as Persons } from "@/assets/icons/persons.svg";
export { default as Star } from "@/assets/icons/star.svg";
export { default as Cat_Drinking } from "@/assets/icons/cat_drinking.svg";
export { default as Close } from "@/assets/icons/Close.svg";
export { default as Signout } from "@/assets/icons/Sign_out_squre.svg";
export { default as Cat_Fitness } from "@/assets/icons/cat_fitness.svg";
export { default as Cat_Mountain_Climb } from "@/assets/icons/cat_mountain_climb.svg";
export { default as Cat_Others } from "@/assets/icons/cat_others.svg";
export { default as Cat_Skateboarding } from "@/assets/icons/cat_skatboarding.svg";
export { default as Cat_Sports } from "@/assets/icons/cat_sports.svg";
export { default as DateIcon } from "@/assets/icons/Date_range.svg";
export { default as ImageIcon } from "@/assets/icons/Img_box_fill.svg";
export { default as LocationIcon } from "@/assets/icons/Pin_alt_fill.svg";
export { default as Clock  } from "@/assets/icons/Time.svg";
export { default as Activity } from "@/assets/icons/Chart_alt.svg";
export { default as ChevronRight } from "@/assets/icons/chevron_right.svg";
export { default as Key } from '@/assets/icons/key.svg';